# Configuration for LangSmith
config:
  langsmithLicenseKey: ""
  apiKeySalt: ""
  authType: "mixed"
  basicAuth:
    enabled: true
    initialOrgAdminEmail: ""
    initialOrgAdminPassword: ""
    jwtSecret: ""


ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip


backend:
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi

frontend:
  service:
    type: ClusterIP  # Use ClusterIP when using Ingress (ALB/nginx) controllers
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi

platformBackend:
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi

playground:
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi

queue:
  replicas: 1
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

postgres:
  persistence:
    enabled: false
  statefulSet:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

redis:
  persistence:
    enabled: false
  statefulSet:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

clickhouse:
  statefulSet:
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
